# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jv1080-qtcreator.ui'
#
# Created: Wed Jun 10 16:23:59 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(906, 560)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 618))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 45, 906, 471))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_common = QtGui.QWidget()
        self.tab_common.setObjectName(_fromUtf8("tab_common"))
        self.groupBox_patchname = QtGui.QGroupBox(self.tab_common)
        self.groupBox_patchname.setGeometry(QtCore.QRect(10, 10, 251, 61))
        self.groupBox_patchname.setObjectName(_fromUtf8("groupBox_patchname"))
        self.line_patchname = QtGui.QLineEdit(self.groupBox_patchname)
        self.line_patchname.setGeometry(QtCore.QRect(10, 20, 111, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.line_patchname.setFont(font)
        self.line_patchname.setText(_fromUtf8(""))
        self.line_patchname.setMaxLength(12)
        self.line_patchname.setObjectName(_fromUtf8("line_patchname"))
        self.button_changename = QtGui.QPushButton(self.groupBox_patchname)
        self.button_changename.setGeometry(QtCore.QRect(130, 20, 111, 25))
        self.button_changename.setObjectName(_fromUtf8("button_changename"))
        self.graphicsView_structure = QtGui.QGraphicsView(self.tab_common)
        self.graphicsView_structure.setGeometry(QtCore.QRect(110, 335, 350, 100))
        self.graphicsView_structure.setFrameShape(QtGui.QFrame.Box)
        self.graphicsView_structure.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsView_structure.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_structure.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_structure.setObjectName(_fromUtf8("graphicsView_structure"))
        self.comboBox_structure = QtGui.QComboBox(self.tab_common)
        self.comboBox_structure.setGeometry(QtCore.QRect(10, 355, 91, 25))
        self.comboBox_structure.setObjectName(_fromUtf8("comboBox_structure"))
        self.label_structure = QtGui.QLabel(self.tab_common)
        self.label_structure.setGeometry(QtCore.QRect(10, 335, 91, 16))
        self.label_structure.setAlignment(QtCore.Qt.AlignCenter)
        self.label_structure.setObjectName(_fromUtf8("label_structure"))
        self.comboBox_boosterlevel = QtGui.QComboBox(self.tab_common)
        self.comboBox_boosterlevel.setGeometry(QtCore.QRect(10, 410, 91, 25))
        self.comboBox_boosterlevel.setObjectName(_fromUtf8("comboBox_boosterlevel"))
        self.label_boosterlevel = QtGui.QLabel(self.tab_common)
        self.label_boosterlevel.setGeometry(QtCore.QRect(10, 390, 91, 16))
        self.label_boosterlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_boosterlevel.setObjectName(_fromUtf8("label_boosterlevel"))
        self.spinBox_tempo = QtGui.QSpinBox(self.tab_common)
        self.spinBox_tempo.setGeometry(QtCore.QRect(280, 30, 86, 25))
        self.spinBox_tempo.setMouseTracking(False)
        self.spinBox_tempo.setAccelerated(True)
        self.spinBox_tempo.setMinimum(20)
        self.spinBox_tempo.setMaximum(250)
        self.spinBox_tempo.setProperty("value", 120)
        self.spinBox_tempo.setObjectName(_fromUtf8("spinBox_tempo"))
        self.label_tempo = QtGui.QLabel(self.tab_common)
        self.label_tempo.setGeometry(QtCore.QRect(280, 10, 86, 16))
        self.label_tempo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempo.setObjectName(_fromUtf8("label_tempo"))
        self.comboBox_octaveshift = QtGui.QComboBox(self.tab_common)
        self.comboBox_octaveshift.setGeometry(QtCore.QRect(385, 30, 86, 25))
        self.comboBox_octaveshift.setObjectName(_fromUtf8("comboBox_octaveshift"))
        self.label_octaveshift = QtGui.QLabel(self.tab_common)
        self.label_octaveshift.setGeometry(QtCore.QRect(385, 10, 86, 16))
        self.label_octaveshift.setAlignment(QtCore.Qt.AlignCenter)
        self.label_octaveshift.setObjectName(_fromUtf8("label_octaveshift"))
        self.comboBox_voicepriority = QtGui.QComboBox(self.tab_common)
        self.comboBox_voicepriority.setGeometry(QtCore.QRect(490, 30, 96, 25))
        self.comboBox_voicepriority.setObjectName(_fromUtf8("comboBox_voicepriority"))
        self.label_voicepriority = QtGui.QLabel(self.tab_common)
        self.label_voicepriority.setGeometry(QtCore.QRect(490, 10, 96, 16))
        self.label_voicepriority.setAlignment(QtCore.Qt.AlignCenter)
        self.label_voicepriority.setObjectName(_fromUtf8("label_voicepriority"))
        self.comboBox_stretchtunedepth = QtGui.QComboBox(self.tab_common)
        self.comboBox_stretchtunedepth.setGeometry(QtCore.QRect(605, 30, 126, 25))
        self.comboBox_stretchtunedepth.setObjectName(_fromUtf8("comboBox_stretchtunedepth"))
        self.comboBox_velocityrangeswitch = QtGui.QComboBox(self.tab_common)
        self.comboBox_velocityrangeswitch.setGeometry(QtCore.QRect(750, 30, 141, 25))
        self.comboBox_velocityrangeswitch.setObjectName(_fromUtf8("comboBox_velocityrangeswitch"))
        self.label_stretchtunedepth = QtGui.QLabel(self.tab_common)
        self.label_stretchtunedepth.setGeometry(QtCore.QRect(605, 10, 126, 16))
        self.label_stretchtunedepth.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stretchtunedepth.setObjectName(_fromUtf8("label_stretchtunedepth"))
        self.label_velocityrangeswitch = QtGui.QLabel(self.tab_common)
        self.label_velocityrangeswitch.setGeometry(QtCore.QRect(750, 10, 141, 16))
        self.label_velocityrangeswitch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangeswitch.setObjectName(_fromUtf8("label_velocityrangeswitch"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_common)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 881, 241))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_patchlevelvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchlevelvalue.setText(_fromUtf8(""))
        self.label_patchlevelvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchlevelvalue.setObjectName(_fromUtf8("label_patchlevelvalue"))
        self.gridLayout_2.addWidget(self.label_patchlevelvalue, 2, 0, 1, 1)
        self.dial_velocitycrossfadedepth = QtGui.QDial(self.gridLayoutWidget)
        self.dial_velocitycrossfadedepth.setMaximum(127)
        self.dial_velocitycrossfadedepth.setObjectName(_fromUtf8("dial_velocitycrossfadedepth"))
        self.gridLayout_2.addWidget(self.dial_velocitycrossfadedepth, 1, 3, 1, 1)
        self.dial_patchlevel = QtGui.QDial(self.gridLayoutWidget)
        self.dial_patchlevel.setMaximum(127)
        self.dial_patchlevel.setProperty("value", 127)
        self.dial_patchlevel.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patchlevel.setInvertedAppearance(False)
        self.dial_patchlevel.setInvertedControls(False)
        self.dial_patchlevel.setObjectName(_fromUtf8("dial_patchlevel"))
        self.gridLayout_2.addWidget(self.dial_patchlevel, 1, 0, 1, 1)
        self.dial_patchpan = QtGui.QDial(self.gridLayoutWidget)
        self.dial_patchpan.setMaximum(127)
        self.dial_patchpan.setProperty("value", 64)
        self.dial_patchpan.setObjectName(_fromUtf8("dial_patchpan"))
        self.gridLayout_2.addWidget(self.dial_patchpan, 1, 1, 1, 1)
        self.dial_analogfeeldepth = QtGui.QDial(self.gridLayoutWidget)
        self.dial_analogfeeldepth.setMaximum(127)
        self.dial_analogfeeldepth.setObjectName(_fromUtf8("dial_analogfeeldepth"))
        self.gridLayout_2.addWidget(self.dial_analogfeeldepth, 1, 2, 1, 1)
        self.dial_keyrangeupper = QtGui.QDial(self.gridLayoutWidget)
        self.dial_keyrangeupper.setMaximum(127)
        self.dial_keyrangeupper.setProperty("value", 127)
        self.dial_keyrangeupper.setObjectName(_fromUtf8("dial_keyrangeupper"))
        self.gridLayout_2.addWidget(self.dial_keyrangeupper, 5, 3, 1, 1)
        self.dial_keyrangelower = QtGui.QDial(self.gridLayoutWidget)
        self.dial_keyrangelower.setMaximum(127)
        self.dial_keyrangelower.setObjectName(_fromUtf8("dial_keyrangelower"))
        self.gridLayout_2.addWidget(self.dial_keyrangelower, 5, 2, 1, 1)
        self.dial_velocityrangeupper = QtGui.QDial(self.gridLayoutWidget)
        self.dial_velocityrangeupper.setMaximum(127)
        self.dial_velocityrangeupper.setProperty("value", 127)
        self.dial_velocityrangeupper.setObjectName(_fromUtf8("dial_velocityrangeupper"))
        self.gridLayout_2.addWidget(self.dial_velocityrangeupper, 5, 1, 1, 1)
        self.dial_velocityrangelower = QtGui.QDial(self.gridLayoutWidget)
        self.dial_velocityrangelower.setMaximum(127)
        self.dial_velocityrangelower.setObjectName(_fromUtf8("dial_velocityrangelower"))
        self.gridLayout_2.addWidget(self.dial_velocityrangelower, 5, 0, 1, 1)
        self.label_velocityrangelowervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangelowervalue.setText(_fromUtf8(""))
        self.label_velocityrangelowervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangelowervalue.setObjectName(_fromUtf8("label_velocityrangelowervalue"))
        self.gridLayout_2.addWidget(self.label_velocityrangelowervalue, 6, 0, 1, 1)
        self.label_velocityrangelower = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangelower.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangelower.setObjectName(_fromUtf8("label_velocityrangelower"))
        self.gridLayout_2.addWidget(self.label_velocityrangelower, 4, 0, 1, 1)
        self.label_patchlevel = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchlevel.setObjectName(_fromUtf8("label_patchlevel"))
        self.gridLayout_2.addWidget(self.label_patchlevel, 0, 0, 1, 1)
        self.label_patchpan = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchpan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchpan.setObjectName(_fromUtf8("label_patchpan"))
        self.gridLayout_2.addWidget(self.label_patchpan, 0, 1, 1, 1)
        self.label_analogfeeldepth = QtGui.QLabel(self.gridLayoutWidget)
        self.label_analogfeeldepth.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analogfeeldepth.setObjectName(_fromUtf8("label_analogfeeldepth"))
        self.gridLayout_2.addWidget(self.label_analogfeeldepth, 0, 2, 1, 1)
        self.label_velocitycrossfadedepth = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocitycrossfadedepth.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocitycrossfadedepth.setObjectName(_fromUtf8("label_velocitycrossfadedepth"))
        self.gridLayout_2.addWidget(self.label_velocitycrossfadedepth, 0, 3, 1, 1)
        self.label_patchpanvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchpanvalue.setText(_fromUtf8(""))
        self.label_patchpanvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchpanvalue.setObjectName(_fromUtf8("label_patchpanvalue"))
        self.gridLayout_2.addWidget(self.label_patchpanvalue, 2, 1, 1, 1)
        self.label_velocityrangeupper = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangeupper.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangeupper.setObjectName(_fromUtf8("label_velocityrangeupper"))
        self.gridLayout_2.addWidget(self.label_velocityrangeupper, 4, 1, 1, 1)
        self.label_analogfeeldepthvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_analogfeeldepthvalue.setText(_fromUtf8(""))
        self.label_analogfeeldepthvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analogfeeldepthvalue.setObjectName(_fromUtf8("label_analogfeeldepthvalue"))
        self.gridLayout_2.addWidget(self.label_analogfeeldepthvalue, 2, 2, 1, 1)
        self.label_keyrangelower = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangelower.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangelower.setObjectName(_fromUtf8("label_keyrangelower"))
        self.gridLayout_2.addWidget(self.label_keyrangelower, 4, 2, 1, 1)
        self.label_velocitycrossfadedepthvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocitycrossfadedepthvalue.setText(_fromUtf8(""))
        self.label_velocitycrossfadedepthvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocitycrossfadedepthvalue.setObjectName(_fromUtf8("label_velocitycrossfadedepthvalue"))
        self.gridLayout_2.addWidget(self.label_velocitycrossfadedepthvalue, 2, 3, 1, 1)
        self.label_keyrangeupper = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangeupper.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangeupper.setObjectName(_fromUtf8("label_keyrangeupper"))
        self.gridLayout_2.addWidget(self.label_keyrangeupper, 4, 3, 1, 1)
        self.label_velocityrangeuppervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangeuppervalue.setText(_fromUtf8(""))
        self.label_velocityrangeuppervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangeuppervalue.setObjectName(_fromUtf8("label_velocityrangeuppervalue"))
        self.gridLayout_2.addWidget(self.label_velocityrangeuppervalue, 6, 1, 1, 1)
        self.label_keyrangelowervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangelowervalue.setText(_fromUtf8(""))
        self.label_keyrangelowervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangelowervalue.setObjectName(_fromUtf8("label_keyrangelowervalue"))
        self.gridLayout_2.addWidget(self.label_keyrangelowervalue, 6, 2, 1, 1)
        self.label_keyrangeuppervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangeuppervalue.setText(_fromUtf8(""))
        self.label_keyrangeuppervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangeuppervalue.setObjectName(_fromUtf8("label_keyrangeuppervalue"))
        self.gridLayout_2.addWidget(self.label_keyrangeuppervalue, 6, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_common, _fromUtf8(""))
        self.tab_effects = QtGui.QWidget()
        self.tab_effects.setObjectName(_fromUtf8("tab_effects"))
        self.comboBox_effectsoutput = QtGui.QComboBox(self.tab_effects)
        self.comboBox_effectsoutput.setGeometry(QtCore.QRect(10, 30, 81, 25))
        self.comboBox_effectsoutput.setObjectName(_fromUtf8("comboBox_effectsoutput"))
        self.label_effectsoutput = QtGui.QLabel(self.tab_effects)
        self.label_effectsoutput.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_effectsoutput.setAlignment(QtCore.Qt.AlignCenter)
        self.label_effectsoutput.setObjectName(_fromUtf8("label_effectsoutput"))
        self.comboBox_EFXoutput = QtGui.QComboBox(self.tab_effects)
        self.comboBox_EFXoutput.setGeometry(QtCore.QRect(100, 30, 81, 25))
        self.comboBox_EFXoutput.setObjectName(_fromUtf8("comboBox_EFXoutput"))
        self.label_EFXoutput = QtGui.QLabel(self.tab_effects)
        self.label_EFXoutput.setGeometry(QtCore.QRect(100, 10, 81, 16))
        self.label_EFXoutput.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EFXoutput.setObjectName(_fromUtf8("label_EFXoutput"))
        self.comboBox_effecttype = QtGui.QComboBox(self.tab_effects)
        self.comboBox_effecttype.setGeometry(QtCore.QRect(190, 30, 196, 25))
        self.comboBox_effecttype.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_effecttype.setObjectName(_fromUtf8("comboBox_effecttype"))
        self.label_effecttype = QtGui.QLabel(self.tab_effects)
        self.label_effecttype.setGeometry(QtCore.QRect(190, 10, 196, 16))
        self.label_effecttype.setAlignment(QtCore.Qt.AlignCenter)
        self.label_effecttype.setObjectName(_fromUtf8("label_effecttype"))
        self.groupBox_patchreverb = QtGui.QGroupBox(self.tab_effects)
        self.groupBox_patchreverb.setGeometry(QtCore.QRect(675, 270, 221, 156))
        self.groupBox_patchreverb.setObjectName(_fromUtf8("groupBox_patchreverb"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_patchreverb)
        self.formLayoutWidget.setGeometry(QtCore.QRect(15, 15, 201, 139))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_patchreverbtype = QtGui.QLabel(self.formLayoutWidget)
        self.label_patchreverbtype.setObjectName(_fromUtf8("label_patchreverbtype"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_patchreverbtype)
        self.label_patchreverbtime = QtGui.QLabel(self.formLayoutWidget)
        self.label_patchreverbtime.setObjectName(_fromUtf8("label_patchreverbtime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_patchreverbtime)
        self.label_patchreverblevel = QtGui.QLabel(self.formLayoutWidget)
        self.label_patchreverblevel.setObjectName(_fromUtf8("label_patchreverblevel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_patchreverblevel)
        self.label_patchreverbdelayfeedback = QtGui.QLabel(self.formLayoutWidget)
        self.label_patchreverbdelayfeedback.setObjectName(_fromUtf8("label_patchreverbdelayfeedback"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_patchreverbdelayfeedback)
        self.label_patchreverbhfdamp = QtGui.QLabel(self.formLayoutWidget)
        self.label_patchreverbhfdamp.setObjectName(_fromUtf8("label_patchreverbhfdamp"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_patchreverbhfdamp)
        self.comboBox_patchreverbtype = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_patchreverbtype.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_patchreverbtype.sizePolicy().hasHeightForWidth())
        self.comboBox_patchreverbtype.setSizePolicy(sizePolicy)
        self.comboBox_patchreverbtype.setObjectName(_fromUtf8("comboBox_patchreverbtype"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_patchreverbtype)
        self.spinBox_patchreverbtime = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_patchreverbtime.setAccelerated(True)
        self.spinBox_patchreverbtime.setMaximum(127)
        self.spinBox_patchreverbtime.setObjectName(_fromUtf8("spinBox_patchreverbtime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_patchreverbtime)
        self.spinBox_patchreverblevel = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_patchreverblevel.setAccelerated(True)
        self.spinBox_patchreverblevel.setMaximum(127)
        self.spinBox_patchreverblevel.setObjectName(_fromUtf8("spinBox_patchreverblevel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBox_patchreverblevel)
        self.spinBox_patchreverbdelayfeedback = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_patchreverbdelayfeedback.setAccelerated(True)
        self.spinBox_patchreverbdelayfeedback.setMaximum(127)
        self.spinBox_patchreverbdelayfeedback.setObjectName(_fromUtf8("spinBox_patchreverbdelayfeedback"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_patchreverbdelayfeedback)
        self.comboBox_patchreverbhfdamp = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_patchreverbhfdamp.setObjectName(_fromUtf8("comboBox_patchreverbhfdamp"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_patchreverbhfdamp)
        self.groupBox_patchchorus = QtGui.QGroupBox(self.tab_effects)
        self.groupBox_patchchorus.setGeometry(QtCore.QRect(675, 80, 221, 186))
        self.groupBox_patchchorus.setObjectName(_fromUtf8("groupBox_patchchorus"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_patchchorus)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(5, 15, 211, 169))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_patchchorusrate = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_patchchorusrate.setObjectName(_fromUtf8("label_patchchorusrate"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_patchchorusrate)
        self.label_patchchorusdepth = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_patchchorusdepth.setObjectName(_fromUtf8("label_patchchorusdepth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_patchchorusdepth)
        self.label_patchchoruspredelay = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_patchchoruspredelay.setObjectName(_fromUtf8("label_patchchoruspredelay"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_patchchoruspredelay)
        self.label_patchchorusfeedback = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_patchchorusfeedback.setObjectName(_fromUtf8("label_patchchorusfeedback"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_patchchorusfeedback)
        self.label_patchchoruslevel = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_patchchoruslevel.setObjectName(_fromUtf8("label_patchchoruslevel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_patchchoruslevel)
        self.label_patchchorusoutputassign = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_patchchorusoutputassign.setObjectName(_fromUtf8("label_patchchorusoutputassign"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_patchchorusoutputassign)
        self.comboBox_patchchorusoutputassign = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_patchchorusoutputassign.setObjectName(_fromUtf8("comboBox_patchchorusoutputassign"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_patchchorusoutputassign)
        self.spinBox_patchchoruslevel = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_patchchoruslevel.setAccelerated(True)
        self.spinBox_patchchoruslevel.setMaximum(127)
        self.spinBox_patchchoruslevel.setObjectName(_fromUtf8("spinBox_patchchoruslevel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.spinBox_patchchoruslevel)
        self.spinBox_patchchorusfeedback = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_patchchorusfeedback.setAccelerated(True)
        self.spinBox_patchchorusfeedback.setMaximum(127)
        self.spinBox_patchchorusfeedback.setObjectName(_fromUtf8("spinBox_patchchorusfeedback"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_patchchorusfeedback)
        self.spinBox_patchchoruspredelay = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_patchchoruspredelay.setAccelerated(True)
        self.spinBox_patchchoruspredelay.setMaximum(127)
        self.spinBox_patchchoruspredelay.setObjectName(_fromUtf8("spinBox_patchchoruspredelay"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBox_patchchoruspredelay)
        self.spinBox_patchchorusdepth = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_patchchorusdepth.setAccelerated(True)
        self.spinBox_patchchorusdepth.setMaximum(127)
        self.spinBox_patchchorusdepth.setObjectName(_fromUtf8("spinBox_patchchorusdepth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_patchchorusdepth)
        self.spinBox_patchchorusrate = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_patchchorusrate.setAccelerated(True)
        self.spinBox_patchchorusrate.setMaximum(127)
        self.spinBox_patchchorusrate.setObjectName(_fromUtf8("spinBox_patchchorusrate"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_patchchorusrate)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_effects)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(5, 80, 666, 361))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dial_efxparameter3 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter3.setObjectName(_fromUtf8("dial_efxparameter3"))
        self.gridLayout_4.addWidget(self.dial_efxparameter3, 1, 2, 1, 1)
        self.dial_efxparameter7 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter7.setObjectName(_fromUtf8("dial_efxparameter7"))
        self.gridLayout_4.addWidget(self.dial_efxparameter7, 6, 2, 1, 1)
        self.dial_efxparameter1 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter1.setObjectName(_fromUtf8("dial_efxparameter1"))
        self.gridLayout_4.addWidget(self.dial_efxparameter1, 1, 0, 1, 1)
        self.dial_efxparameter11 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter11.setObjectName(_fromUtf8("dial_efxparameter11"))
        self.gridLayout_4.addWidget(self.dial_efxparameter11, 10, 2, 1, 1)
        self.dial_efxparameter12 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter12.setObjectName(_fromUtf8("dial_efxparameter12"))
        self.gridLayout_4.addWidget(self.dial_efxparameter12, 10, 3, 1, 1)
        self.label_efxparameter5value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter5value.setText(_fromUtf8(""))
        self.label_efxparameter5value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter5value.setObjectName(_fromUtf8("label_efxparameter5value"))
        self.gridLayout_4.addWidget(self.label_efxparameter5value, 7, 0, 1, 1)
        self.dial_efxparameter10 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter10.setObjectName(_fromUtf8("dial_efxparameter10"))
        self.gridLayout_4.addWidget(self.dial_efxparameter10, 10, 1, 1, 1)
        self.dial_efxparameter5 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter5.setObjectName(_fromUtf8("dial_efxparameter5"))
        self.gridLayout_4.addWidget(self.dial_efxparameter5, 6, 0, 1, 1)
        self.label_efxparameter9value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter9value.setText(_fromUtf8(""))
        self.label_efxparameter9value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter9value.setObjectName(_fromUtf8("label_efxparameter9value"))
        self.gridLayout_4.addWidget(self.label_efxparameter9value, 11, 0, 1, 1)
        self.label_efxparameter1value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter1value.setText(_fromUtf8(""))
        self.label_efxparameter1value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter1value.setObjectName(_fromUtf8("label_efxparameter1value"))
        self.gridLayout_4.addWidget(self.label_efxparameter1value, 2, 0, 1, 1)
        self.dial_efxparameter6 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter6.setObjectName(_fromUtf8("dial_efxparameter6"))
        self.gridLayout_4.addWidget(self.dial_efxparameter6, 6, 1, 1, 1)
        self.label_efxparameter9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter9.setText(_fromUtf8(""))
        self.label_efxparameter9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter9.setObjectName(_fromUtf8("label_efxparameter9"))
        self.gridLayout_4.addWidget(self.label_efxparameter9, 9, 0, 1, 1)
        self.dial_efxparameter9 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter9.setObjectName(_fromUtf8("dial_efxparameter9"))
        self.gridLayout_4.addWidget(self.dial_efxparameter9, 10, 0, 1, 1)
        self.label_efxparameter1 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter1.setText(_fromUtf8(""))
        self.label_efxparameter1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter1.setObjectName(_fromUtf8("label_efxparameter1"))
        self.gridLayout_4.addWidget(self.label_efxparameter1, 0, 0, 1, 1)
        self.dial_efxparameter8 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter8.setObjectName(_fromUtf8("dial_efxparameter8"))
        self.gridLayout_4.addWidget(self.dial_efxparameter8, 6, 3, 1, 1)
        self.label_efxparameter5 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter5.setText(_fromUtf8(""))
        self.label_efxparameter5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter5.setObjectName(_fromUtf8("label_efxparameter5"))
        self.gridLayout_4.addWidget(self.label_efxparameter5, 4, 0, 1, 1)
        self.dial_efxparameter2 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter2.setObjectName(_fromUtf8("dial_efxparameter2"))
        self.gridLayout_4.addWidget(self.dial_efxparameter2, 1, 1, 1, 1)
        self.dial_efxparameter4 = QtGui.QDial(self.gridLayoutWidget_3)
        self.dial_efxparameter4.setObjectName(_fromUtf8("dial_efxparameter4"))
        self.gridLayout_4.addWidget(self.dial_efxparameter4, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 8, 0, 1, 1)
        self.label_efxparameter10value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter10value.setText(_fromUtf8(""))
        self.label_efxparameter10value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter10value.setObjectName(_fromUtf8("label_efxparameter10value"))
        self.gridLayout_4.addWidget(self.label_efxparameter10value, 11, 1, 1, 1)
        self.label_efxparameter11value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter11value.setText(_fromUtf8(""))
        self.label_efxparameter11value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter11value.setObjectName(_fromUtf8("label_efxparameter11value"))
        self.gridLayout_4.addWidget(self.label_efxparameter11value, 11, 2, 1, 1)
        self.label_efxparameter12value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter12value.setText(_fromUtf8(""))
        self.label_efxparameter12value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter12value.setObjectName(_fromUtf8("label_efxparameter12value"))
        self.gridLayout_4.addWidget(self.label_efxparameter12value, 11, 3, 1, 1)
        self.label_efxparameter10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter10.setText(_fromUtf8(""))
        self.label_efxparameter10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter10.setObjectName(_fromUtf8("label_efxparameter10"))
        self.gridLayout_4.addWidget(self.label_efxparameter10, 9, 1, 1, 1)
        self.label_efxparameter11 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter11.setText(_fromUtf8(""))
        self.label_efxparameter11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter11.setObjectName(_fromUtf8("label_efxparameter11"))
        self.gridLayout_4.addWidget(self.label_efxparameter11, 9, 2, 1, 1)
        self.label_efxparameter12 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter12.setText(_fromUtf8(""))
        self.label_efxparameter12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter12.setObjectName(_fromUtf8("label_efxparameter12"))
        self.gridLayout_4.addWidget(self.label_efxparameter12, 9, 3, 1, 1)
        self.label_efxparameter6value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter6value.setText(_fromUtf8(""))
        self.label_efxparameter6value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter6value.setObjectName(_fromUtf8("label_efxparameter6value"))
        self.gridLayout_4.addWidget(self.label_efxparameter6value, 7, 1, 1, 1)
        self.label_efxparameter7value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter7value.setText(_fromUtf8(""))
        self.label_efxparameter7value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter7value.setObjectName(_fromUtf8("label_efxparameter7value"))
        self.gridLayout_4.addWidget(self.label_efxparameter7value, 7, 2, 1, 1)
        self.label_efxparameter8value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter8value.setText(_fromUtf8(""))
        self.label_efxparameter8value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter8value.setObjectName(_fromUtf8("label_efxparameter8value"))
        self.gridLayout_4.addWidget(self.label_efxparameter8value, 7, 3, 1, 1)
        self.label_efxparameter6 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter6.setText(_fromUtf8(""))
        self.label_efxparameter6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter6.setObjectName(_fromUtf8("label_efxparameter6"))
        self.gridLayout_4.addWidget(self.label_efxparameter6, 4, 1, 1, 1)
        self.label_efxparameter7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter7.setText(_fromUtf8(""))
        self.label_efxparameter7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter7.setObjectName(_fromUtf8("label_efxparameter7"))
        self.gridLayout_4.addWidget(self.label_efxparameter7, 4, 2, 1, 1)
        self.label_efxparameter8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter8.setText(_fromUtf8(""))
        self.label_efxparameter8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter8.setObjectName(_fromUtf8("label_efxparameter8"))
        self.gridLayout_4.addWidget(self.label_efxparameter8, 4, 3, 1, 1)
        self.label_efxparameter2value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter2value.setText(_fromUtf8(""))
        self.label_efxparameter2value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter2value.setObjectName(_fromUtf8("label_efxparameter2value"))
        self.gridLayout_4.addWidget(self.label_efxparameter2value, 2, 1, 1, 1)
        self.label_efxparameter3value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter3value.setText(_fromUtf8(""))
        self.label_efxparameter3value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter3value.setObjectName(_fromUtf8("label_efxparameter3value"))
        self.gridLayout_4.addWidget(self.label_efxparameter3value, 2, 2, 1, 1)
        self.label_efxparameter4value = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter4value.setText(_fromUtf8(""))
        self.label_efxparameter4value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter4value.setObjectName(_fromUtf8("label_efxparameter4value"))
        self.gridLayout_4.addWidget(self.label_efxparameter4value, 2, 3, 1, 1)
        self.label_efxparameter2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter2.setText(_fromUtf8(""))
        self.label_efxparameter2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter2.setObjectName(_fromUtf8("label_efxparameter2"))
        self.gridLayout_4.addWidget(self.label_efxparameter2, 0, 1, 1, 1)
        self.label_efxparameter3 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter3.setText(_fromUtf8(""))
        self.label_efxparameter3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter3.setObjectName(_fromUtf8("label_efxparameter3"))
        self.gridLayout_4.addWidget(self.label_efxparameter3, 0, 2, 1, 1)
        self.label_efxparameter4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_efxparameter4.setText(_fromUtf8(""))
        self.label_efxparameter4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_efxparameter4.setObjectName(_fromUtf8("label_efxparameter4"))
        self.gridLayout_4.addWidget(self.label_efxparameter4, 0, 3, 1, 1)
        self.groupBox_efxcontrol = QtGui.QGroupBox(self.tab_effects)
        self.groupBox_efxcontrol.setGeometry(QtCore.QRect(575, 10, 321, 66))
        self.groupBox_efxcontrol.setObjectName(_fromUtf8("groupBox_efxcontrol"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_efxcontrol)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 15, 311, 45))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.spinBox_efxcontrol2 = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_efxcontrol2.sizePolicy().hasHeightForWidth())
        self.spinBox_efxcontrol2.setSizePolicy(sizePolicy)
        self.spinBox_efxcontrol2.setAccelerated(True)
        self.spinBox_efxcontrol2.setMinimum(-63)
        self.spinBox_efxcontrol2.setMaximum(63)
        self.spinBox_efxcontrol2.setObjectName(_fromUtf8("spinBox_efxcontrol2"))
        self.gridLayout_5.addWidget(self.spinBox_efxcontrol2, 1, 3, 1, 1)
        self.spinBox_efxcontrol1 = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_efxcontrol1.sizePolicy().hasHeightForWidth())
        self.spinBox_efxcontrol1.setSizePolicy(sizePolicy)
        self.spinBox_efxcontrol1.setAccelerated(True)
        self.spinBox_efxcontrol1.setMinimum(-63)
        self.spinBox_efxcontrol1.setMaximum(63)
        self.spinBox_efxcontrol1.setObjectName(_fromUtf8("spinBox_efxcontrol1"))
        self.gridLayout_5.addWidget(self.spinBox_efxcontrol1, 1, 1, 1, 1)
        self.comboBox_efxcontrol1 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_efxcontrol1.setObjectName(_fromUtf8("comboBox_efxcontrol1"))
        self.gridLayout_5.addWidget(self.comboBox_efxcontrol1, 1, 0, 1, 1)
        self.comboBox_efxcontrol2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_efxcontrol2.setObjectName(_fromUtf8("comboBox_efxcontrol2"))
        self.gridLayout_5.addWidget(self.comboBox_efxcontrol2, 1, 2, 1, 1)
        self.label_efxcontrol1 = QtGui.QLabel(self.layoutWidget)
        self.label_efxcontrol1.setText(_fromUtf8(""))
        self.label_efxcontrol1.setObjectName(_fromUtf8("label_efxcontrol1"))
        self.gridLayout_5.addWidget(self.label_efxcontrol1, 0, 0, 1, 2)
        self.label_efxcontrol2 = QtGui.QLabel(self.layoutWidget)
        self.label_efxcontrol2.setText(_fromUtf8(""))
        self.label_efxcontrol2.setObjectName(_fromUtf8("label_efxcontrol2"))
        self.gridLayout_5.addWidget(self.label_efxcontrol2, 0, 2, 1, 2)
        self.spinBox_chorussendlevel = QtGui.QSpinBox(self.tab_effects)
        self.spinBox_chorussendlevel.setGeometry(QtCore.QRect(395, 30, 81, 25))
        self.spinBox_chorussendlevel.setAccelerated(True)
        self.spinBox_chorussendlevel.setMaximum(127)
        self.spinBox_chorussendlevel.setObjectName(_fromUtf8("spinBox_chorussendlevel"))
        self.spinBox_reverbsendlevel = QtGui.QSpinBox(self.tab_effects)
        self.spinBox_reverbsendlevel.setGeometry(QtCore.QRect(490, 30, 81, 25))
        self.spinBox_reverbsendlevel.setAccelerated(True)
        self.spinBox_reverbsendlevel.setMaximum(127)
        self.spinBox_reverbsendlevel.setObjectName(_fromUtf8("spinBox_reverbsendlevel"))
        self.label_chorussendlevel = QtGui.QLabel(self.tab_effects)
        self.label_chorussendlevel.setGeometry(QtCore.QRect(395, 10, 81, 16))
        self.label_chorussendlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_chorussendlevel.setObjectName(_fromUtf8("label_chorussendlevel"))
        self.label_reverbsendlevel = QtGui.QLabel(self.tab_effects)
        self.label_reverbsendlevel.setGeometry(QtCore.QRect(490, 10, 81, 16))
        self.label_reverbsendlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reverbsendlevel.setObjectName(_fromUtf8("label_reverbsendlevel"))
        self.spinBox_outputlevel = QtGui.QSpinBox(self.tab_effects)
        self.spinBox_outputlevel.setGeometry(QtCore.QRect(10, 55, 81, 25))
        self.spinBox_outputlevel.setObjectName(_fromUtf8("spinBox_outputlevel"))
        self.spinBox_efxoutputlevel = QtGui.QSpinBox(self.tab_effects)
        self.spinBox_efxoutputlevel.setGeometry(QtCore.QRect(100, 55, 81, 25))
        self.spinBox_efxoutputlevel.setObjectName(_fromUtf8("spinBox_efxoutputlevel"))
        self.spinBox_EFXchorussendlevel = QtGui.QSpinBox(self.tab_effects)
        self.spinBox_EFXchorussendlevel.setGeometry(QtCore.QRect(395, 55, 81, 25))
        self.spinBox_EFXchorussendlevel.setAccelerated(True)
        self.spinBox_EFXchorussendlevel.setMaximum(127)
        self.spinBox_EFXchorussendlevel.setObjectName(_fromUtf8("spinBox_EFXchorussendlevel"))
        self.spinBox_EFXreverbsendlevel = QtGui.QSpinBox(self.tab_effects)
        self.spinBox_EFXreverbsendlevel.setGeometry(QtCore.QRect(490, 55, 81, 25))
        self.spinBox_EFXreverbsendlevel.setAccelerated(True)
        self.spinBox_EFXreverbsendlevel.setMaximum(127)
        self.spinBox_EFXreverbsendlevel.setObjectName(_fromUtf8("spinBox_EFXreverbsendlevel"))
        self.tabWidget.addTab(self.tab_effects, _fromUtf8(""))
        self.tab_control = QtGui.QWidget()
        self.tab_control.setObjectName(_fromUtf8("tab_control"))
        self.tabWidget.addTab(self.tab_control, _fromUtf8(""))
        self.tab_wave = QtGui.QWidget()
        self.tab_wave.setObjectName(_fromUtf8("tab_wave"))
        self.tabWidget.addTab(self.tab_wave, _fromUtf8(""))
        self.tab_lfo = QtGui.QWidget()
        self.tab_lfo.setObjectName(_fromUtf8("tab_lfo"))
        self.tabWidget.addTab(self.tab_lfo, _fromUtf8(""))
        self.tab_pitch = QtGui.QWidget()
        self.tab_pitch.setObjectName(_fromUtf8("tab_pitch"))
        self.tabWidget.addTab(self.tab_pitch, _fromUtf8(""))
        self.tab_tvf = QtGui.QWidget()
        self.tab_tvf.setObjectName(_fromUtf8("tab_tvf"))
        self.tabWidget.addTab(self.tab_tvf, _fromUtf8(""))
        self.tab_tva = QtGui.QWidget()
        self.tab_tva.setObjectName(_fromUtf8("tab_tva"))
        self.tabWidget.addTab(self.tab_tva, _fromUtf8(""))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(755, 5, 146, 57))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_toneselect1 = QtGui.QLabel(self.layoutWidget1)
        self.label_toneselect1.setObjectName(_fromUtf8("label_toneselect1"))
        self.gridLayout.addWidget(self.label_toneselect1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_toneselect2 = QtGui.QLabel(self.layoutWidget1)
        self.label_toneselect2.setObjectName(_fromUtf8("label_toneselect2"))
        self.gridLayout.addWidget(self.label_toneselect2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_toneselect3 = QtGui.QLabel(self.layoutWidget1)
        self.label_toneselect3.setObjectName(_fromUtf8("label_toneselect3"))
        self.gridLayout.addWidget(self.label_toneselect3, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_toneselect4 = QtGui.QLabel(self.layoutWidget1)
        self.label_toneselect4.setObjectName(_fromUtf8("label_toneselect4"))
        self.gridLayout.addWidget(self.label_toneselect4, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_tone1 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_tone1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_tone1.setText(_fromUtf8(""))
        self.checkBox_tone1.setChecked(True)
        self.checkBox_tone1.setObjectName(_fromUtf8("checkBox_tone1"))
        self.gridLayout.addWidget(self.checkBox_tone1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_tone2 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_tone2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_tone2.setText(_fromUtf8(""))
        self.checkBox_tone2.setObjectName(_fromUtf8("checkBox_tone2"))
        self.gridLayout.addWidget(self.checkBox_tone2, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_tone3 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_tone3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_tone3.setText(_fromUtf8(""))
        self.checkBox_tone3.setObjectName(_fromUtf8("checkBox_tone3"))
        self.gridLayout.addWidget(self.checkBox_tone3, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_tone4 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_tone4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_tone4.setText(_fromUtf8(""))
        self.checkBox_tone4.setObjectName(_fromUtf8("checkBox_tone4"))
        self.gridLayout.addWidget(self.checkBox_tone4, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_toneselect = QtGui.QLabel(self.layoutWidget1)
        self.label_toneselect.setObjectName(_fromUtf8("label_toneselect"))
        self.gridLayout.addWidget(self.label_toneselect, 0, 0, 1, 4, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.dial_patchlevel, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_patchlevelvalue.setNum)
        QtCore.QObject.connect(self.dial_patchpan, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_patchpanvalue.setNum)
        QtCore.QObject.connect(self.dial_analogfeeldepth, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_analogfeeldepthvalue.setNum)
        QtCore.QObject.connect(self.dial_velocitycrossfadedepth, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_velocitycrossfadedepthvalue.setNum)
        QtCore.QObject.connect(self.dial_velocityrangelower, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_velocityrangelowervalue.setNum)
        QtCore.QObject.connect(self.dial_velocityrangeupper, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_velocityrangeuppervalue.setNum)
        QtCore.QObject.connect(self.dial_keyrangelower, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_keyrangelowervalue.setNum)
        QtCore.QObject.connect(self.dial_keyrangeupper, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_keyrangeuppervalue.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "JV1080 Patch Editor", None))
        self.groupBox_patchname.setTitle(_translate("MainWindow", "Patch Name", None))
        self.line_patchname.setInputMask(_translate("MainWindow", "nnnnnnnnnnnn", None))
        self.line_patchname.setPlaceholderText(_translate("MainWindow", "12 Chars Max", None))
        self.button_changename.setText(_translate("MainWindow", "Change Name", None))
        self.label_structure.setText(_translate("MainWindow", "Structure", None))
        self.label_boosterlevel.setText(_translate("MainWindow", "Booster Level", None))
        self.spinBox_tempo.setSuffix(_translate("MainWindow", " BPM", None))
        self.label_tempo.setText(_translate("MainWindow", "Patch Tempo", None))
        self.label_octaveshift.setText(_translate("MainWindow", "Octave Shift", None))
        self.label_voicepriority.setText(_translate("MainWindow", "Voice Priority", None))
        self.label_stretchtunedepth.setText(_translate("MainWindow", "Stretch Tune Depth", None))
        self.label_velocityrangeswitch.setText(_translate("MainWindow", "Velocity Range Switch", None))
        self.label_velocityrangelower.setText(_translate("MainWindow", "Velocity Range Lower", None))
        self.label_patchlevel.setText(_translate("MainWindow", "Patch Level", None))
        self.label_patchpan.setText(_translate("MainWindow", "Patch Pan", None))
        self.label_analogfeeldepth.setText(_translate("MainWindow", "Analog Feel Depth", None))
        self.label_velocitycrossfadedepth.setText(_translate("MainWindow", "Velocity Cross Fade Depth", None))
        self.label_velocityrangeupper.setText(_translate("MainWindow", "Velocity Range Upper", None))
        self.label_keyrangelower.setText(_translate("MainWindow", "Key Range Lower", None))
        self.label_keyrangeupper.setText(_translate("MainWindow", "Key Range Upper", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_common), _translate("MainWindow", "Common", None))
        self.label_effectsoutput.setText(_translate("MainWindow", "Output", None))
        self.label_EFXoutput.setText(_translate("MainWindow", "EFX Output", None))
        self.label_effecttype.setText(_translate("MainWindow", "Effect Type", None))
        self.groupBox_patchreverb.setTitle(_translate("MainWindow", "Patch Reverb", None))
        self.label_patchreverbtype.setText(_translate("MainWindow", "Reverb Type", None))
        self.label_patchreverbtime.setText(_translate("MainWindow", "Reverb Time", None))
        self.label_patchreverblevel.setText(_translate("MainWindow", "Reverb Level", None))
        self.label_patchreverbdelayfeedback.setText(_translate("MainWindow", "Delay Feedback", None))
        self.label_patchreverbhfdamp.setText(_translate("MainWindow", "HF Damp", None))
        self.groupBox_patchchorus.setTitle(_translate("MainWindow", "Patch Chorus", None))
        self.label_patchchorusrate.setText(_translate("MainWindow", "Chorus Rate", None))
        self.label_patchchorusdepth.setText(_translate("MainWindow", "Chorus Depth", None))
        self.label_patchchoruspredelay.setText(_translate("MainWindow", "Pre-Delay", None))
        self.label_patchchorusfeedback.setText(_translate("MainWindow", "Chorus Feedback", None))
        self.label_patchchoruslevel.setText(_translate("MainWindow", "Chorus Level", None))
        self.label_patchchorusoutputassign.setText(_translate("MainWindow", "Output Assign", None))
        self.groupBox_efxcontrol.setTitle(_translate("MainWindow", "EFX Control", None))
        self.spinBox_chorussendlevel.setPrefix(_translate("MainWindow", "Tone ", None))
        self.spinBox_reverbsendlevel.setPrefix(_translate("MainWindow", "Tone ", None))
        self.label_chorussendlevel.setText(_translate("MainWindow", "Chorus Send", None))
        self.label_reverbsendlevel.setText(_translate("MainWindow", "Reverb Send", None))
        self.spinBox_EFXchorussendlevel.setPrefix(_translate("MainWindow", "EFX ", None))
        self.spinBox_EFXreverbsendlevel.setPrefix(_translate("MainWindow", "EFX ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_effects), _translate("MainWindow", "Effects", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), _translate("MainWindow", "Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wave), _translate("MainWindow", "Wave", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lfo), _translate("MainWindow", "LFO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pitch), _translate("MainWindow", "Pitch", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tvf), _translate("MainWindow", "TVF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tva), _translate("MainWindow", "TVA", None))
        self.label_toneselect1.setText(_translate("MainWindow", "1", None))
        self.label_toneselect2.setText(_translate("MainWindow", "2", None))
        self.label_toneselect3.setText(_translate("MainWindow", "3", None))
        self.label_toneselect4.setText(_translate("MainWindow", "4", None))
        self.label_toneselect.setText(_translate("MainWindow", "_____Tone Select_____", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    app.setStyle('Plastique')
    Form = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

