# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jv1080.ui'
#
# Created: Wed May 20 11:29:37 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import jvparams as jvp

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(636, 480)
        TabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tab_common = QtGui.QWidget()
        self.tab_common.setObjectName(_fromUtf8("tab_common"))
        self.groupBox_patchname = QtGui.QGroupBox(self.tab_common)
        self.groupBox_patchname.setGeometry(QtCore.QRect(10, 10, 251, 61))
        self.groupBox_patchname.setObjectName(_fromUtf8("groupBox_patchname"))
        self.line_patchname = QtGui.QLineEdit(self.groupBox_patchname)
        self.line_patchname.setGeometry(QtCore.QRect(10, 20, 111, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.line_patchname.setFont(font)
        self.line_patchname.setText(_fromUtf8(""))
        self.line_patchname.setMaxLength(12)
        self.line_patchname.setObjectName(_fromUtf8("line_patchname"))
        self.button_changename = QtGui.QPushButton(self.groupBox_patchname)
        self.button_changename.setGeometry(QtCore.QRect(130, 20, 111, 25))
        self.button_changename.setObjectName(_fromUtf8("button_changename"))
        self.groupBox_tempo = QtGui.QGroupBox(self.tab_common)
        self.groupBox_tempo.setGeometry(QtCore.QRect(270, 10, 101, 61))
        self.groupBox_tempo.setObjectName(_fromUtf8("groupBox_tempo"))
        self.spinBox_tempo = QtGui.QSpinBox(self.groupBox_tempo)
        self.spinBox_tempo.setGeometry(QtCore.QRect(10, 20, 81, 25))
        self.spinBox_tempo.setMinimum(20)
        self.spinBox_tempo.setMaximum(250)
        self.spinBox_tempo.setObjectName(_fromUtf8("spinBox_tempo"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_common)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 611, 221))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dial_keyrangelower = QtGui.QDial(self.gridLayoutWidget)
        self.dial_keyrangelower.setObjectName(_fromUtf8("dial_keyrangelower"))
        self.gridLayout.addWidget(self.dial_keyrangelower, 5, 2, 1, 1)
        self.dial_velocityrangeupper = QtGui.QDial(self.gridLayoutWidget)
        self.dial_velocityrangeupper.setObjectName(_fromUtf8("dial_velocityrangeupper"))
        self.gridLayout.addWidget(self.dial_velocityrangeupper, 5, 1, 1, 1)
        self.dial_patchpan = QtGui.QDial(self.gridLayoutWidget)
        self.dial_patchpan.setObjectName(_fromUtf8("dial_patchpan"))
        self.gridLayout.addWidget(self.dial_patchpan, 1, 1, 1, 1)
        self.dial_analogfeeldepth = QtGui.QDial(self.gridLayoutWidget)
        self.dial_analogfeeldepth.setMaximum(127)
        self.dial_analogfeeldepth.setObjectName(_fromUtf8("dial_analogfeeldepth"))
        self.gridLayout.addWidget(self.dial_analogfeeldepth, 1, 2, 1, 1)
        self.dial_patchlevel = QtGui.QDial(self.gridLayoutWidget)
        self.dial_patchlevel.setMaximum(127)
        self.dial_patchlevel.setObjectName(_fromUtf8("dial_patchlevel"))
        self.gridLayout.addWidget(self.dial_patchlevel, 1, 0, 1, 1)
        self.dial_velcrossfadedepth = QtGui.QDial(self.gridLayoutWidget)
        self.dial_velcrossfadedepth.setObjectName(_fromUtf8("dial_velcrossfadedepth"))
        self.gridLayout.addWidget(self.dial_velcrossfadedepth, 1, 3, 1, 1)
        self.dial_velocityrangelower = QtGui.QDial(self.gridLayoutWidget)
        self.dial_velocityrangelower.setObjectName(_fromUtf8("dial_velocityrangelower"))
        self.gridLayout.addWidget(self.dial_velocityrangelower, 5, 0, 1, 1)
        self.dial_keyrangeupper = QtGui.QDial(self.gridLayoutWidget)
        self.dial_keyrangeupper.setObjectName(_fromUtf8("dial_keyrangeupper"))
        self.gridLayout.addWidget(self.dial_keyrangeupper, 5, 3, 1, 1)
        self.label_patchlevelvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchlevelvalue.setText(_fromUtf8(""))
        self.label_patchlevelvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchlevelvalue.setObjectName(_fromUtf8("label_patchlevelvalue"))
        self.gridLayout.addWidget(self.label_patchlevelvalue, 2, 0, 1, 1)
        self.label_patchlevel = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchlevel.setObjectName(_fromUtf8("label_patchlevel"))
        self.gridLayout.addWidget(self.label_patchlevel, 0, 0, 1, 1)
        self.label_patchpan = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchpan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchpan.setObjectName(_fromUtf8("label_patchpan"))
        self.gridLayout.addWidget(self.label_patchpan, 0, 1, 1, 1)
        self.label_analogfeel = QtGui.QLabel(self.gridLayoutWidget)
        self.label_analogfeel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analogfeel.setObjectName(_fromUtf8("label_analogfeel"))
        self.gridLayout.addWidget(self.label_analogfeel, 0, 2, 1, 1)
        self.label_velcrossfadedepth = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velcrossfadedepth.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velcrossfadedepth.setObjectName(_fromUtf8("label_velcrossfadedepth"))
        self.gridLayout.addWidget(self.label_velcrossfadedepth, 0, 3, 1, 1)
        self.label_velocityrangelowervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangelowervalue.setText(_fromUtf8(""))
        self.label_velocityrangelowervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangelowervalue.setObjectName(_fromUtf8("label_velocityrangelowervalue"))
        self.gridLayout.addWidget(self.label_velocityrangelowervalue, 6, 0, 1, 1)
        self.label_velocityrangeuppervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangeuppervalue.setText(_fromUtf8(""))
        self.label_velocityrangeuppervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangeuppervalue.setObjectName(_fromUtf8("label_velocityrangeuppervalue"))
        self.gridLayout.addWidget(self.label_velocityrangeuppervalue, 6, 1, 1, 1)
        self.label_keyrangelowervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangelowervalue.setText(_fromUtf8(""))
        self.label_keyrangelowervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangelowervalue.setObjectName(_fromUtf8("label_keyrangelowervalue"))
        self.gridLayout.addWidget(self.label_keyrangelowervalue, 6, 2, 1, 1)
        self.label_keyrangeuppervalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangeuppervalue.setText(_fromUtf8(""))
        self.label_keyrangeuppervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangeuppervalue.setObjectName(_fromUtf8("label_keyrangeuppervalue"))
        self.gridLayout.addWidget(self.label_keyrangeuppervalue, 6, 3, 1, 1)
        self.label_velocityrangelower = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangelower.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangelower.setObjectName(_fromUtf8("label_velocityrangelower"))
        self.gridLayout.addWidget(self.label_velocityrangelower, 4, 0, 1, 1)
        self.label_patchpanvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_patchpanvalue.setText(_fromUtf8(""))
        self.label_patchpanvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patchpanvalue.setObjectName(_fromUtf8("label_patchpanvalue"))
        self.gridLayout.addWidget(self.label_patchpanvalue, 2, 1, 1, 1)
        self.label_velocityrangeupper = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velocityrangeupper.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velocityrangeupper.setObjectName(_fromUtf8("label_velocityrangeupper"))
        self.gridLayout.addWidget(self.label_velocityrangeupper, 4, 1, 1, 1)
        self.label_analogfeelvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_analogfeelvalue.setText(_fromUtf8(""))
        self.label_analogfeelvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analogfeelvalue.setObjectName(_fromUtf8("label_analogfeelvalue"))
        self.gridLayout.addWidget(self.label_analogfeelvalue, 2, 2, 1, 1)
        self.label_keyrangelower = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangelower.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangelower.setObjectName(_fromUtf8("label_keyrangelower"))
        self.gridLayout.addWidget(self.label_keyrangelower, 4, 2, 1, 1)
        self.label_velcrossfadedepthvalue = QtGui.QLabel(self.gridLayoutWidget)
        self.label_velcrossfadedepthvalue.setText(_fromUtf8(""))
        self.label_velcrossfadedepthvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_velcrossfadedepthvalue.setObjectName(_fromUtf8("label_velcrossfadedepthvalue"))
        self.gridLayout.addWidget(self.label_velcrossfadedepthvalue, 2, 3, 1, 1)
        self.label_keyrangeupper = QtGui.QLabel(self.gridLayoutWidget)
        self.label_keyrangeupper.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyrangeupper.setObjectName(_fromUtf8("label_keyrangeupper"))
        self.gridLayout.addWidget(self.label_keyrangeupper, 4, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.tab_common)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 310, 251, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboBox_voicepriority = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_voicepriority.setObjectName(_fromUtf8("comboBox_voicepriority"))
        self.gridLayout_2.addWidget(self.comboBox_voicepriority, 1, 1, 1, 1)
        self.label_velocityrangeswitch = QtGui.QLabel(self.layoutWidget)
        self.label_velocityrangeswitch.setObjectName(_fromUtf8("label_velocityrangeswitch"))
        self.gridLayout_2.addWidget(self.label_velocityrangeswitch, 3, 1, 1, 1)
        self.label_octaveshift = QtGui.QLabel(self.layoutWidget)
        self.label_octaveshift.setObjectName(_fromUtf8("label_octaveshift"))
        self.gridLayout_2.addWidget(self.label_octaveshift, 0, 0, 1, 1)
        self.comboBox_velocityrangeswitch = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_velocityrangeswitch.setObjectName(_fromUtf8("comboBox_velocityrangeswitch"))
        self.gridLayout_2.addWidget(self.comboBox_velocityrangeswitch, 4, 1, 1, 1)
        self.label_structure = QtGui.QLabel(self.layoutWidget)
        self.label_structure.setObjectName(_fromUtf8("label_structure"))
        self.gridLayout_2.addWidget(self.label_structure, 0, 2, 1, 1)
        self.comboBox_structure = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_structure.setObjectName(_fromUtf8("comboBox_structure"))
        self.gridLayout_2.addWidget(self.comboBox_structure, 1, 2, 1, 1)
        self.label_boosterlevel = QtGui.QLabel(self.layoutWidget)
        self.label_boosterlevel.setObjectName(_fromUtf8("label_boosterlevel"))
        self.gridLayout_2.addWidget(self.label_boosterlevel, 3, 2, 1, 1)
        self.comboBox_boosterlevel = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_boosterlevel.setObjectName(_fromUtf8("comboBox_boosterlevel"))
        self.gridLayout_2.addWidget(self.comboBox_boosterlevel, 4, 2, 1, 1)
        self.label_stretchtunedepth = QtGui.QLabel(self.layoutWidget)
        self.label_stretchtunedepth.setObjectName(_fromUtf8("label_stretchtunedepth"))
        self.gridLayout_2.addWidget(self.label_stretchtunedepth, 3, 0, 1, 1)
        self.comboBox_stretchtunedepth = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_stretchtunedepth.setObjectName(_fromUtf8("comboBox_stretchtunedepth"))
        self.gridLayout_2.addWidget(self.comboBox_stretchtunedepth, 4, 0, 1, 1)
        self.comboBox_octaveshift = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_octaveshift.setObjectName(_fromUtf8("comboBox_octaveshift"))
        self.gridLayout_2.addWidget(self.comboBox_octaveshift, 1, 0, 1, 1)
        self.label_voicepriority = QtGui.QLabel(self.layoutWidget)
        self.label_voicepriority.setObjectName(_fromUtf8("label_voicepriority"))
        self.gridLayout_2.addWidget(self.label_voicepriority, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.graphicsView_structure = QtGui.QGraphicsView(self.tab_common)
        self.graphicsView_structure.setGeometry(QtCore.QRect(270, 320, 350, 100))
        self.graphicsView_structure.setFrameShape(QtGui.QFrame.Box)
        self.graphicsView_structure.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsView_structure.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_structure.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_structure.setObjectName(_fromUtf8("graphicsView_structure"))
        TabWidget.addTab(self.tab_common, _fromUtf8(""))
        self.tab_effects = QtGui.QWidget()
        self.tab_effects.setObjectName(_fromUtf8("tab_effects"))
        TabWidget.addTab(self.tab_effects, _fromUtf8(""))
        self.tab_control = QtGui.QWidget()
        self.tab_control.setObjectName(_fromUtf8("tab_control"))
        TabWidget.addTab(self.tab_control, _fromUtf8(""))
        self.tab_wave = QtGui.QWidget()
        self.tab_wave.setObjectName(_fromUtf8("tab_wave"))
        TabWidget.addTab(self.tab_wave, _fromUtf8(""))
        self.tab_lfo = QtGui.QWidget()
        self.tab_lfo.setObjectName(_fromUtf8("tab_lfo"))
        TabWidget.addTab(self.tab_lfo, _fromUtf8(""))
        self.tab_pitch = QtGui.QWidget()
        self.tab_pitch.setObjectName(_fromUtf8("tab_pitch"))
        TabWidget.addTab(self.tab_pitch, _fromUtf8(""))
        self.tab_tvf = QtGui.QWidget()
        self.tab_tvf.setObjectName(_fromUtf8("tab_tvf"))
        TabWidget.addTab(self.tab_tvf, _fromUtf8(""))
        self.tab_tva = QtGui.QWidget()
        self.tab_tva.setObjectName(_fromUtf8("tab_tva"))
        TabWidget.addTab(self.tab_tva, _fromUtf8(""))

        self.comboBox_boosterlevel.addItems(jvp.PATCH_COMMON_PARAMS['Booster Level'])
        self.comboBox_octaveshift.addItems(jvp.PATCH_COMMON_PARAMS['Octave Shift'])
        self.comboBox_stretchtunedepth.addItems(jvp.PATCH_COMMON_PARAMS['Stretch Tune Depth'])
        self.comboBox_structure.addItems(jvp.PATCH_COMMON_PARAMS['Structure'])
        self.comboBox_velocityrangeswitch.addItems(jvp.PATCH_COMMON_PARAMS['Velocity Range Switch'])
        self.comboBox_voicepriority.addItems(jvp.PATCH_COMMON_PARAMS['Voice Priority'])
        
        self.update_structure_image()

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.dial_patchlevel, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_patchlevelvalue.setNum)
        QtCore.QObject.connect(self.dial_patchpan, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_patchpanvalue.setNum)
        QtCore.QObject.connect(self.dial_analogfeeldepth, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_analogfeelvalue.setNum)
        QtCore.QObject.connect(self.dial_velcrossfadedepth, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_velcrossfadedepthvalue.setNum)
        QtCore.QObject.connect(self.dial_velocityrangelower, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_velocityrangelowervalue.setNum)
        QtCore.QObject.connect(self.dial_velocityrangeupper, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_velocityrangeuppervalue.setNum)
        QtCore.QObject.connect(self.dial_keyrangelower, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_keyrangelowervalue.setNum)
        QtCore.QObject.connect(self.dial_keyrangeupper, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_keyrangeuppervalue.setNum)
        QtCore.QObject.connect(self.comboBox_structure, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.update_structure_image)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def update_structure_image(self):
        self.structureImage = QtGui.QPixmap()
        self.structureImage.load('../img/structure' + self.comboBox_structure.currentText() + '.png')
        self.structureScene = QtGui.QGraphicsScene()
        self.structureScene.addPixmap(self.structureImage)
        self.graphicsView_structure.setScene(self.structureScene)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.groupBox_patchname.setTitle(_translate("TabWidget", "Patch Name", None))
        self.line_patchname.setInputMask(_translate("TabWidget", "nnnnnnnnnnnn; ", None))
        self.line_patchname.setPlaceholderText(_translate("TabWidget", "12 Chars Max", None))
        self.button_changename.setText(_translate("TabWidget", "Change Name", None))
        self.groupBox_tempo.setTitle(_translate("TabWidget", "Patch Tempo", None))
        self.spinBox_tempo.setSuffix(_translate("TabWidget", " BPM", None))
        self.label_patchlevel.setText(_translate("TabWidget", "Patch Level", None))
        self.label_patchpan.setText(_translate("TabWidget", "Patch Pan", None))
        self.label_analogfeel.setText(_translate("TabWidget", "Analog Feel Depth", None))
        self.label_velcrossfadedepth.setText(_translate("TabWidget", "Vel Cross Fade Depth", None))
        self.label_velocityrangelower.setText(_translate("TabWidget", "Velocity Range Lower", None))
        self.label_velocityrangeupper.setText(_translate("TabWidget", "Velocity Range Upper", None))
        self.label_keyrangelower.setText(_translate("TabWidget", "Key Range Lower", None))
        self.label_keyrangeupper.setText(_translate("TabWidget", "Key Range Upper", None))
        self.label_velocityrangeswitch.setText(_translate("TabWidget", "Velocity Range Switch", None))
        self.label_octaveshift.setText(_translate("TabWidget", "Octave Shift", None))
        self.label_structure.setText(_translate("TabWidget", "Structure", None))
        self.label_boosterlevel.setText(_translate("TabWidget", "Booster Level", None))
        self.label_stretchtunedepth.setText(_translate("TabWidget", "Stretch Tune Depth", None))
        self.label_voicepriority.setText(_translate("TabWidget", "Voice Priority", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_common), _translate("TabWidget", "COMMON", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_effects), _translate("TabWidget", "EFFECTS", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_control), _translate("TabWidget", "CONTROL", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_wave), _translate("TabWidget", "WAVE", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_lfo), _translate("TabWidget", "LFO", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_pitch), _translate("TabWidget", "PITCH", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_tvf), _translate("TabWidget", "TVF", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_tva), _translate("TabWidget", "TVA", None))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())